name: orcaslicer
title: OrcaSlicer
version: 0.1 # version will be set by craftctl later
#adopt-info: part-orcaslicer
summary: Orca Slicer is an open source slicer for FDM printers.
description: |
  OrcaSlicer is fork of Bambu Studio
  It was previously known as BambuStudio-SoftFever
  Bambu Studio is forked from PrusaSlicer by Prusa Research, which is from Slic3r by Alessandro Ranellucci and the RepRap community. Orca Slicer incorporates a lot of features from SuperSlicer by @supermerill Orca Slicer's logo is designed by community member Justin Levine(@freejstnalxndr)
grade: devel # devel/stable
confinement: devmode # devmode/classic/strict
type: app
base: core22

architectures:
  - build-on: amd64
    build-for: amd64
  #- build-on: [amd64, arm64]
  #  build-for: arm64
  #- build-on: [amd64, ppc64el]
  #  build-for: ppc64el
  #- build-on: [amd64, s390x]
  #  build-for: s390x

apps:
  orcaslicer:
  command: orcaslicer
  plugs: [ home, network ]

parts:
  part-orcaslicer:
    plugin: nil
    #source: .
    #parse-info: [snap/local/fcbnetmap.metainfo.xml]

